version: '3.8'

services:

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8004:8000"
    volumes:
      - C:\Users\shobh\Desktop\side_project\celery_task:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0