version: '3.8'

services:

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.worker.celery worker --loglevel=info --logfile=app/logs/celery.log --concurrency=2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
